server:
  port: 80
spring:
  application:
    #这个名字关系到注册到注册服务器后的名字
    name: consumer-order
eureka:
  client:
    #false表示不用去注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心，我的职责是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与EUREKA Server 交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone:
        http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
